FROM python:3.6
ENV LANG=C.UTF-8 LC_ALL=C.UTF-8
ENV RABBITMQ_DEFAULT_USER=user
ENV RABBITMQ_DEFAULT_PASS=password
ENV CELERY_BROKER=amqp://user:password@broker:5672
ENV FLOWER_BROKER=amqp://user:password@broker:5672
ENV RESULT_BACKEND=rpc://
ENV CELERY_RESULT_BACKEND=django-db

WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
RUN rm requirements.txt

EXPOSE 8000

COPY /app .

CMD gunicorn -w 4 api.wsgi -b 0.0.0.0:8000