version: '2'
# Copia de docker-compose.prod.yml
# Editado "hub.mobeats.com.ar/" de las images para que al buildear utilice las locales
services:
  app:
    image: middleware_garantizar/api:latest
    ports:
    - 8812:8000/tcp
    depends_on:
    - migration
    - mysql
  migration:
    image: middleware_garantizar/api:latest
    command: python manage.py migrate --noinput
    depends_on:
    - mysql
  fogarmock:
    image: middleware_garantizar/mock_fogar:latest
  garantizarmock:
    image: middleware_garantizar/mock_garantizar:latest
  workersalida:
    image: middleware_garantizar/worker_salida:latest
  workerentrada:
    image: middleware_garantizar/worker_entrada:latest
    environment:
      URL_FOGAR_ALTA: http://qa-foga.mobeats.com.ar/fogabonita/Api/processInfo
      URL_FOGAR_ACTUALIZACION: http://qa-foga.mobeats.com.ar/fogabonita/Api/processEdition
  mysql:
    image: mysql:5
    environment:
      MYSQL_DATABASE: garantizar
      MYSQL_PASSWORD: dbg4r4nt1z4r
      MYSQL_ROOT_PASSWORD: dbg4r4nt1z4r
      MYSQL_USER: garantizar
    volumes:
    - mysql_data:/var/lib/mysql
    ports:
    - 3306:3306/tcp
  broker:
    image: rabbitmq:3
    environment:
      RABBITMQ_DEFAULT_PASS: password
      RABBITMQ_DEFAULT_USER: user
    volumes:
    - rabbit_data:/var/lib/rabbitmq/mnesia
    ports:
    - 5672:5672/tcp
    - 15672:15672/tcp
  flower:
    image: zoomeranalytics/flower:0.9.1-4.0.2
    environment:
      FLOWER_BROKER: amqp://user:password@broker:5672
    ports:
    - 5555:5555/tcp
volumes:
  rabbit_data:
  mysql_data:

