# Generated by Django 2.0.7 on 2018-11-20 20:19

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_operacion', models.CharField(choices=[('ALTA', 'alta'), ('ACTUALIZACION', 'actualizacion')], default='ALTA', max_length=15)),
                ('total_operaciones', models.PositiveIntegerField(default=0)),
                ('total_encoladas', models.PositiveIntegerField(default=0, null=True)),
                ('total_no_encoladas', models.PositiveIntegerField(default=0, null=True)),
                ('total_encoladas_por_procesar', models.PositiveIntegerField(default=0, null=True)),
                ('total_registro_previo', models.PositiveIntegerField(default=0, null=True)),
                ('resultado_enviado_garantizar', models.BooleanField(default=False)),
                ('respuesta_garantizar', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Operaciones',
            },
            bases=(models.Model, api.models.UpdateMixin),
        ),
        migrations.CreateModel(
            name='OperacionDetalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_garantizar', models.CharField(db_index=True, max_length=100, null=True, unique=True)),
                ('procesado', models.BooleanField(default=False)),
                ('resultado_fogar', models.TextField(blank=True)),
                ('operacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Operacion')),
            ],
            bases=(models.Model, api.models.UpdateMixin),
        ),
        migrations.CreateModel(
            name='OperacionDetalleHistorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procesado', models.BooleanField(default=False)),
                ('resultado_fogar', models.TextField(blank=True)),
                ('identifier', models.PositiveIntegerField(default=0, unique=True)),
                ('operacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Operacion')),
                ('operacionDetalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.OperacionDetalle')),
            ],
            options={
                'verbose_name_plural': 'Historial de operaciones detalle',
            },
            bases=(models.Model, api.models.UpdateMixin),
        ),
        migrations.CreateModel(
            name='OperacionEncoladaError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_garantizar', models.CharField(db_index=True, max_length=100, null=True)),
                ('trace', models.TextField(blank=True)),
                ('operacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Operacion')),
            ],
            options={
                'verbose_name_plural': 'Errores de operaciones detalle',
            },
            bases=(models.Model, api.models.UpdateMixin),
        ),
        migrations.AddIndex(
            model_name='operaciondetallehistorial',
            index=models.Index(fields=['identifier'], name='api_operaci_identif_6e3a90_idx'),
        ),
        migrations.AddIndex(
            model_name='operaciondetalle',
            index=models.Index(fields=['id_garantizar'], name='api_operaci_id_gara_fb2bc3_idx'),
        ),
    ]
