# Generated by Django 2.0.7 on 2018-11-22 17:40

import api.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GarantizarFogar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_garantizar', models.CharField(db_index=True, max_length=100)),
                ('id_fogar', models.CharField(db_index=True, max_length=100)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
            bases=(models.Model, api.models.UpdateMixin),
        ),
        migrations.AddField(
            model_name='operacion',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='operaciondetalle',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='operaciondetallehistorial',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='operacionencoladaerror',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterUniqueTogether(
            name='garantizarfogar',
            unique_together={('id_garantizar', 'id_fogar')},
        ),
    ]
