# Generated by Django 2.0.7 on 2018-11-28 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20181122_1740'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='garantizarfogar',
            options={'verbose_name_plural': 'Relacion Garantizar-Fogar'},
        ),
        migrations.AddField(
            model_name='operacion',
            name='url_respuesta',
            field=models.TextField(blank=True),
        ),
    ]
