# Generated by Django 2.0.7 on 2018-11-28 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20181128_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='operaciondetalle',
            name='representacion_json',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='operaciondetallehistorial',
            name='representacion_json',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='operacionencoladaerror',
            name='representacion_json',
            field=models.TextField(blank=True),
        ),
    ]
