# Generated by Django 2.0.7 on 2018-12-03 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_operaciondetalle_status_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operaciondetalle',
            name='status_code',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
