# Generated by Django 2.0.7 on 2018-12-03 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20181203_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operaciondetalle',
            name='status_code',
            field=models.CharField(blank=True, max_length=3),
        ),
    ]
