# Generated by Django 2.0.7 on 2018-12-12 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_operacion_representacion_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='operacion',
            name='resultado_generado_para_garantizar',
            field=models.TextField(blank=True),
        ),
    ]
