# Generated by Django 2.0.7 on 2018-12-12 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_operacion_resultado_generado_para_garantizar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operacion',
            old_name='respuesta_garantizar',
            new_name='respuesta_garantizar_json',
        ),
        migrations.RenameField(
            model_name='operacion',
            old_name='resultado_generado_para_garantizar',
            new_name='resultado_generado_garantizar_json',
        ),
        migrations.RenameField(
            model_name='operaciondetalle',
            old_name='resultado_fogar',
            new_name='resultado_fogar_json',
        ),
        migrations.RenameField(
            model_name='operaciondetallehistorial',
            old_name='resultado_fogar',
            new_name='resultado_fogar_json',
        ),
        migrations.AddField(
            model_name='operaciondetalle',
            name='resultado_fogar_raw',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='operaciondetallehistorial',
            name='resultado_fogar_raw',
            field=models.TextField(blank=True),
        ),
    ]
